### ISSUE TITLE
Clicking on node in Jacks viewer disables text selection on rest of page

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-portal#1144]
Clicking on a node in the Jacks viewer disables the ability to highlight and select text anywhere else on the page.

To test:
 1. On the slice page, click on 'Details' for any of the aggregates. (Alternatively, go to an Add Resources results page if it's available.)
 1. Highlight and select some text on the page. Deselect.
 1. On the Jacks viewer, click on a node and move it within the canvas.
 1. Try selecting text again on the page as before. The text doesn't highlight.

This appears to affect Chrome and Firefox on both Mac and Ubuntu.

 _Imported from trac ticket [#1144](http://trac.gpolab.bbn.com/proto-ch/ticket/1144),  created by bujcich on 08-06-2014 at 14:48, last modified: 03-04-2015 at 09:28_

**Comment by ahelsing** [comment]
This is an issue in Jacks itself. I will get it into the pipeline to be looked into.

_Trac comment by kdownie on 08-08-2014 at 12:09_

**Comment by ahelsing** [comment]
Jon says this should be fixed in latest Jacks.

_Trac comment by ahelsing on 09-22-2014 at 11:27_

**Comment by ahelsing** [comment]
This remains a problem.

_Trac comment by ahelsing on 09-30-2014 at 14:34_

**Comment by ahelsing** [comment]
Jon says: `My current (bogus) workaround is to set things to selectable whenever they click view rspec. I will keep trying to track down the real bug.`

_Trac comment by ahelsing on 09-30-2014 at 14:45_

**Comment by tcmitchell** [comment]
This is still an issue but isn't near the top of the GEC 21 list of things to fix. Bumping it back.

_Trac comment by tmitchel (github user: tcmitchell) on 10-08-2014 at 11:47_

**Comment by ahelsing** [comment]
Last issue here was in Firefox, and Jon has now fixed this.

_Trac comment by ahelsing on 03-04-2015 at 09:28_
